### ISSUE TITLE
Use "All Time Since Today"

### ISSUE THREAD

**Issue by MacroPower** [MacroPower/wakatime_exporter#1]
For the total metric, switch to sourcing from the all_time_since_today endpoint. This is available for all users and means you will get some metrics pseudo-backfilled.

**Comment by MacroPower** [comment]
Naming this `cumulative_seconds_total` for now.

**Comment by MacroPower** [comment]
Closed in https://github.com/MacroPower/wakatime_exporter/commit/0880a39e252a0406dec52481ddca3a758c767a5e

**Comment by alanhamlett** [comment]
Related, we've opened the API for all date ranges. You can query Summaries, Durations, and Heartbeats for non-Premium users back until their account was created. Dates before the user was created will just always return zero seconds.

Only the dashboard now limits date range queries, not the API 😄

**Comment by MacroPower** [comment]
Thank you @alanhamlett, that is awesome! I will take a look at that soon for sure. I think that could really improve the quality of this exporter's metrics. In addition to the obvious, if we don't have to reset all the time it will get rid of the accuracy lost from using non-initialized counters, which will be *super* nice when using rate functions. 🙂
