### ISSUE TITLE
About a prometheus and grafana docker stack

### ISSUE THREAD

**Issue by bsormagec** [MacroPower/wakatime_exporter#10]
Hello can you create an example docker stack how to use this ? I can't build it.

**Comment by MacroPower** [comment]
Hello and apologies for the delay. I'm not sure what you mean when you say you can't build it. You can get a docker image from [here](https://hub.docker.com/r/macropower/wakatime-exporter), so you shouldn't have to build it for yourself.

If you're asking for like a compose stack with Grafana and Prometheus, I would say that's out of scope of this repo. But others have created this, [vegasbrianc/prometheus](https://github.com/vegasbrianc/prometheus) for example. You would just need to run the container I linked and add the /metrics endpoint exposed by wakatime_exporter as a scrape target in the Prometheus config.

Hopefully this helped. If you run into a specific issue, please post the exact error you're getting (i.e. screenshots) and I will do my best to respond.

**Comment by MacroPower** [comment]
@bsormagec Is there anything else I can help with? If not, I'm going to close this issue in a couple days. Thanks

**Comment by bsormagec** [comment]
I tried it but can't completely run with grafana dashboard :( i wanna see my team's work with this but can't get single data yet. @MacroPower

**Comment by MacroPower** [comment]
@bsormagec Could you explain what you've done so far? Did you get any errors? What do you get when you visit the exporter's /metrics endpoint in your browser (you should be able to see the raw data there)?

**Comment by luckydonald** [comment]
I found this tool, and never having used Grafana and Prometheus before, a `docker-compose.yml` to get one started would make a difference for me.

**Comment by MacroPower** [comment]
I changed my mind on this and ended up adding a really simple docker-compose setup. Hopefully that helps you guys / future people get things set up.
