### ISSUE TITLE
Dashboard issue

### ISSUE THREAD

**Issue by Joshuaharry120** [MacroPower/wakatime_exporter#11]
If I import the dashboard, I get the following error.

Templating init failed
invalid parameter "query": 1:94: parse error: missing unit character in duration

**Comment by MacroPower** [comment]
@Joshuaharry120 What version of Grafana are you running? I just added a docker-compose file to the repo, and on the latest Grafana I'm not seeing that issue. I tried with a few other versions but wasn't able to replicate this.

**Comment by Joshuaharry120** [comment]
> @Joshuaharry120 What version of Grafana are you running? I just added a docker-compose file to the repo, and on the latest Grafana I'm not seeing that issue. I tried with a few other versions but wasn't able to replicate this.


Hi mate,

I managed to fix this it was because i was running garfna 5, updated to latest version, it works now apart from 3 fields .

Wakatime Rank
Daily Goal Progress
Weekly Goal Progress  

https://itsjosh.xyz/ss/u/sBI5rmQ9ZDJaUfjVeTA0koP.png
Josh

**Comment by MacroPower** [comment]
@Joshuaharry120 I think that's probably all correct. For the goals to work you have to have created them on wakatime.com and have some progress towards them. Rank only records the top 5000 users (or something like that) so you probably just need to use it more and you'll eventually get on there.
