### ISSUE TITLE
404 Errors with Wakapi

### ISSUE THREAD

**Issue by guillaumearnx** [MacroPower/wakatime_exporter#14]
Hello,

There are some errors with the api (404 http)

Maybe is it normal ?
Here is my config

Thank's

![image](https://github.com/MacroPower/wakatime_exporter/assets/37373941/b743bfd9-d4f8-4ddb-a80c-5f431d8bbdf1)

![image](https://github.com/MacroPower/wakatime_exporter/assets/37373941/50ee77de-8688-4768-862d-b46779f4bc2c)

**Comment by MacroPower** [comment]
Hello @guillaumearnx - My guess based on the [current wakapi docs](https://wakapi.dev/swagger-ui/swagger-ui/index.html), you'll need to specify:

`--wakatime.scrape-uri="https://wakapi.dev/api/compat/wakatime/v1"`

to get the Wakatime-compatible API.

**Comment by guillaumearnx** [comment]
Thank's 
Now i've some other errors.

![image](https://github.com/MacroPower/wakatime_exporter/assets/37373941/a545779c-491a-4311-8de1-99526de279e0)

But i can't see in the docs anywhere a query with "leaders" or "goals". Can we assume that wakapi does not support these requests and that only waketime does?

**Comment by MacroPower** [comment]
That would be safe to assume. You can disable those collectors pretty easily to avoid those errors. e.g.:

```sh
export WAKA_COLLECTOR_GOAL="false"
export WAKA_COLLECTOR_LEADER="false"
```

or via arguments.

**Comment by MacroPower** [comment]
Closing but let me know if you have any other questions!
